package entity;
// Generated 24/05/2018 03:21:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

    private int idUsuarios;
    private Usuarios usuarios;
    private Set peticions = new HashSet(0);
    private Set ejercicios = new HashSet(0);
    private Set grupos = new HashSet(0);
    private String grupo;

    public Alumno() {
    }

    public Alumno(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public Alumno(Usuarios usuarios, Set peticions, Set ejercicios, Set grupos) {
        this.usuarios = usuarios;
        this.peticions = peticions;
        this.ejercicios = ejercicios;
        this.grupos = grupos;
    }

    public int getIdUsuarios() {
        return this.idUsuarios;
    }

    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }

    public String getGrupo() {
        return grupo;
    }

    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }

    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public Set getPeticions() {
        return this.peticions;
    }

    public void setPeticions(Set peticions) {
        this.peticions = peticions;
    }

    public Set getEjercicios() {
        return this.ejercicios;
    }

    public void setEjercicios(Set ejercicios) {
        this.ejercicios = ejercicios;
    }

    public Set getGrupos() {
        return this.grupos;
    }

    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }

    public String grupoS() {
        Grupo x = null;
        for (Iterator it = grupos.iterator(); it.hasNext();) {
            x = (Grupo) it.next();
        }
        try {
            if (x.getNombre() != null) {
                return x.getNombre();
            } else {
                return "Ninguno";
            }
        } catch (Exception e) {
        }
        return "Ninguno";
    }

}
