package entity;
// Generated 24/05/2018 03:21:53 PM by Hibernate Tools 4.3.1



/**
 * Peticion generated by hbm2java
 */
public class Peticion  implements java.io.Serializable {


     private Integer idPeticion;
     private Alumno alumno;
     private Grupo grupo;
     private Integer aceptacion;

    public Peticion() {
    }

    public Peticion(Alumno alumno, Grupo grupo, Integer aceptacion) {
       this.alumno = alumno;
       this.grupo = grupo;
       this.aceptacion = aceptacion;
    }
   
    public Integer getIdPeticion() {
        return this.idPeticion;
    }
    
    public void setIdPeticion(Integer idPeticion) {
        this.idPeticion = idPeticion;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Integer getAceptacion() {
        return this.aceptacion;
    }
    
    public void setAceptacion(Integer aceptacion) {
        this.aceptacion = aceptacion;
    }




}


