package entity;
// Generated 24/05/2018 03:21:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ejercicio generated by hbm2java
 */
public class Ejercicio  implements java.io.Serializable {


     private Integer idEjercicio;
     private Profesor profesor;
     private Set grupos = new HashSet(0);
     private Set alumnos = new HashSet(0);

    public Ejercicio() {
    }

    public Ejercicio(Profesor profesor, Set grupos, Set alumnos) {
       this.profesor = profesor;
       this.grupos = grupos;
       this.alumnos = alumnos;
    }
   
    public Integer getIdEjercicio() {
        return this.idEjercicio;
    }
    
    public void setIdEjercicio(Integer idEjercicio) {
        this.idEjercicio = idEjercicio;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


