package entity;
// Generated 24/05/2018 03:21:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private Profesor profesor;
     private String nombre;
     private String contraseña;
     private Set peticions = new HashSet(0);
     private Set ejercicios = new HashSet(0);
     private Set alumnos = new HashSet(0);

    public Grupo() {
    }

    public Grupo(Profesor profesor, String nombre, String contraseña, Set peticions, Set ejercicios, Set alumnos) {
       this.profesor = profesor;
       this.nombre = nombre;
       this.contraseña = contraseña;
       this.peticions = peticions;
       this.ejercicios = ejercicios;
       this.alumnos = alumnos;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }
    public Set getPeticions() {
        return this.peticions;
    }
    
    public void setPeticions(Set peticions) {
        this.peticions = peticions;
    }
    public Set getEjercicios() {
        return this.ejercicios;
    }
    
    public void setEjercicios(Set ejercicios) {
        this.ejercicios = ejercicios;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


