package entity;
// Generated 24/05/2018 03:21:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

    private int idUsuarios;
    private Usuarios usuarios;
    private Set grupos = new HashSet(0);
    private Set preejercicios = new HashSet(0);
    private Set ejercicios = new HashSet(0);
    private String grupo;
    private boolean editable;

    public Profesor() {
    }

    public String getGrupo() {
        return grupo;
    }

    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }

    public boolean isEditable() {
        return editable;
    }

    public void setEditable(boolean editable) {
        this.editable = editable;
    }

    public Profesor(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public Profesor(Usuarios usuarios, Set grupos, Set preejercicios, Set ejercicios) {
        this.usuarios = usuarios;
        this.grupos = grupos;
        this.preejercicios = preejercicios;
        this.ejercicios = ejercicios;
    }

    public int getIdUsuarios() {
        return this.idUsuarios;
    }

    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }

    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public Set getGrupos() {
        return this.grupos;
    }

    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }

    public Set getPreejercicios() {
        return this.preejercicios;
    }

    public void setPreejercicios(Set preejercicios) {
        this.preejercicios = preejercicios;
    }

    public Set getEjercicios() {
        return this.ejercicios;
    }

    public void setEjercicios(Set ejercicios) {
        this.ejercicios = ejercicios;
    }

    public String grupo() {
        Grupo x = null;
        for (Iterator it = grupos.iterator(); it.hasNext();) {
            x = (Grupo) it.next();
        }
        try {
            if (x.getNombre() != null) {
                return x.getNombre();
            } else {
                return "Ninguno";
            }
        } catch (Exception e) {
        }
        return "Ninguno";
    }

}
