package entity;
// Generated 16/05/2018 10:27:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int idRol;
     private String tipo;
     private Set usuarioses = new HashSet(0);

    public Rol() {
    }

	
    public Rol(int idRol) {
        this.idRol = idRol;
    }
    public Rol(int idRol, String tipo, Set usuarioses) {
       this.idRol = idRol;
       this.tipo = tipo;
       this.usuarioses = usuarioses;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


